services:
  zookeeper-origin:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-origin
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka-origin:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-origin
    depends_on:
      - zookeeper-origin
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-origin:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka-origin:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-origin:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper-dest:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-dest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182

  kafka-dest:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-dest
    depends_on:
      - zookeeper-dest
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-dest:2182
      KAFKA_LISTENERS: PLAINTEXT://kafka-dest:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-dest:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.5.0
    container_name: kafka-connect
    depends_on:
      - kafka-origin
      - kafka-dest
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka-origin:9092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "connect-mm2"
      CONNECT_CONFIG_STORAGE_TOPIC: "_connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "_connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "_connect-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1

      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"

      CONNECT_PLUGIN_PATH: "/usr/share/java"

      # IMPORTANTE: MirrorMaker2 ya viene incluido
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/connectors"]
      interval: 5s
      retries: 20

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka-origin
      - kafka-dest
      - kafka-connect
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "origin"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-origin:9092"
      KAFKA_CLUSTERS_1_NAME: "dest"
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: "kafka-dest:9093"
      KAFKA_CLUSTERS_2_NAME: "connect"
      KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS: "kafka-origin:9092"
      KAFKA_CLUSTERS_2_KAFKACONNECT_0_NAME: "connect"
      KAFKA_CLUSTERS_2_KAFKACONNECT_0_ADDRESS: "http://kafka-connect:8083"
